"""
prepare_forecast_data.py

This script prepares the cleaned workload dataset for SARIMA forecasting.

Expected input:
    data/interim/cleaned_data.parquet

Expected output:
    data/processed/sarima_ready_dataset.parquet

Forecasting approach:
    - Use scheduled_time as the time reference.
    - Aggregate workloads into 15-minute windows.
    - Forecast resource demand by job_type.
    - Prepare CPU, memory, and runtime metrics for modeling.
"""

from pathlib import Path

import pandas as pd


INPUT_PATH = Path("data/interim/cleaned_data.parquet")
OUTPUT_PATH = Path("data/processed/sarima_ready_dataset.parquet")

FORECAST_WINDOW = "15min"

REQUIRED_COLUMNS = [
    "instance_sn",
    "scheduled_time",
    "cpu_request",
    "memory_request",
    "duration_minutes",
    "job_type",
]


def load_dataset(input_path: Path) -> pd.DataFrame:
    """Load the cleaned dataset generated by the data cleaning pipeline."""
    if not input_path.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_path}. "
            "Run src/data/load_and_merge_data.py and src/data/clean_data.py first."
        )

    return pd.read_parquet(input_path)


def validate_columns(df: pd.DataFrame) -> None:
    """Validate that all required columns exist in the dataset."""
    missing_columns = [col for col in REQUIRED_COLUMNS if col not in df.columns]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}. "
            f"Expected columns are: {REQUIRED_COLUMNS}. "
            f"Available columns are: {list(df.columns)}"
        )


def prepare_time_series_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepare 15-minute forecasting windows.

    Since the original trace uses relative time values, scheduled_time is converted
    from timedelta into a timestamp-like index starting from a fixed reference date.

    The dataset is aggregated by:
        - 15-minute forecasting window
        - job_type

    Metrics created:
        - avg_cpu_request
        - avg_memory_request
        - avg_duration_minutes
        - job_count
    """

    df = df.copy()

    reference_start = pd.Timestamp("2025-01-01 00:00:00")

    df["forecast_timestamp"] = reference_start + df["scheduled_time"]

    df = df.sort_values("forecast_timestamp")

    aggregated_df = (
        df.set_index("forecast_timestamp")
        .groupby("job_type")
        .resample(FORECAST_WINDOW)
        .agg(
            avg_cpu_request=("cpu_request", "mean"),
            avg_memory_request=("memory_request", "mean"),
            avg_duration_minutes=("duration_minutes", "mean"),
            job_count=("instance_sn", "count"),
        )
        .reset_index()
    )

    metric_columns = [
        "avg_cpu_request",
        "avg_memory_request",
        "avg_duration_minutes",
        "job_count",
    ]

    aggregated_df[metric_columns] = (
        aggregated_df.groupby("job_type")[metric_columns]
        .transform(lambda group: group.interpolate(method="linear").ffill().bfill())
    )

    aggregated_df = aggregated_df.dropna().sort_values(
        ["job_type", "forecast_timestamp"]
    )

    return aggregated_df


def save_dataset(df: pd.DataFrame, output_path: Path) -> None:
    """Save the SARIMA-ready forecasting dataset."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(output_path, index=False)


def main() -> None:
    """Run the forecasting data preparation pipeline."""
    df = load_dataset(INPUT_PATH)
    validate_columns(df)

    sarima_ready_df = prepare_time_series_data(df)
    save_dataset(sarima_ready_df, OUTPUT_PATH)

    print(f"SARIMA-ready dataset saved to: {OUTPUT_PATH}")
    print(f"Rows saved: {len(sarima_ready_df)}")

    print("\nColumns:")
    print(list(sarima_ready_df.columns))

    print("\nSample:")
    print(sarima_ready_df.head())


if __name__ == "__main__":
    main()