"""
build_jobs_json_from_forecast.py

Translates job-level forecast output into the JSON structure expected by
the optimization model.

Input:
    data/processed/optimization_forecast_jobs.parquet

Output:
    data/processed/optimization_jobs_params.json
"""

from pathlib import Path
import json
import math

import pandas as pd


INPUT_PATH = Path("data/processed/optimization_forecast_jobs.parquet")
OUTPUT_PATH = Path("data/processed/optimization_jobs_params.json")

SLOT_SECONDS = 900
HORIZON_SECONDS = 86_400
HORIZON_SLOTS = 96

GPU_SERVERS = list(range(0, 34))
CPU_SERVERS = list(range(34, 42))



def load_forecast_jobs(input_path: Path) -> pd.DataFrame:
    """Load forecast jobs generated by forecast_model.py."""

    if not input_path.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_path}. "
            "Run forecast_model.py first."
        )

    return pd.read_parquet(input_path)


def validate_forecast_schema(df: pd.DataFrame) -> None:
    """Validate required columns for optimization translation."""

    required_columns = [
        "forecast_job_id",
        "instance_sn",
        "role",
        "app_name",
        "job_type",
        "release_seconds",
        "cpu_request",
        "memory_request",
        "gpu_request",
        "processing_duration_seconds",
        "deadline_seconds",
        "is_critical",
        "replica_count",
    ]

    missing_columns = [
        column for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}. "
            f"Available columns: {list(df.columns)}"
        )


def clean_forecast_jobs(df: pd.DataFrame) -> pd.DataFrame:
    """Clean and filter forecast jobs for the optimization model."""

    jobs = df.copy()

    jobs["job_type"] = jobs["job_type"].astype(str).str.lower().str.strip()

    numeric_columns = [
        "release_seconds",
        "cpu_request",
        "memory_request",
        "gpu_request",
        "processing_duration_seconds",
        "deadline_seconds",
        "is_critical",
        "replica_count",
    ]

    for column in numeric_columns:
        jobs[column] = pd.to_numeric(jobs[column], errors="coerce")

    jobs = jobs.dropna(subset=numeric_columns)

    jobs = jobs[
        (jobs["release_seconds"] >= 0)
        & (jobs["release_seconds"] < HORIZON_SECONDS)
        & (jobs["processing_duration_seconds"] > 0)
        & (jobs["cpu_request"] > 0)
        & (jobs["memory_request"] > 0)
    ].copy()

    jobs = jobs.sort_values("release_seconds").reset_index(drop=True)


    return jobs


def seconds_to_release_slot(seconds: float) -> int:
    """Convert release seconds into optimization slot index."""

    return max(
        0,
        int(math.floor(seconds / SLOT_SECONDS)),
    )


def seconds_to_duration_slots(seconds: float) -> int:
    """Convert processing duration seconds into slot duration."""

    return max(
        1,
        int(math.ceil(seconds / SLOT_SECONDS)),
    )


def seconds_to_deadline_slot(seconds: float) -> int:
    """Convert deadline seconds into optimization slot index."""

    return min(
        HORIZON_SLOTS,
        int(math.ceil(seconds / SLOT_SECONDS)),
    )


def build_resource_requirements(jobs: pd.DataFrame) -> dict[int, float]:
    """
    Build normalized resource requirement r[i].

    The optimization model expects a single normalized load value between 0 and 1.
    This combines CPU and memory demand using equal weight.
    """

    max_cpu = 128 #cores (from server parameters based on G type server with highest CPU capacity)
    max_memory = 1024  # GB (from server parameters based on G type server with highest RAM capacity)

    resource_requirement = {}

    for i, row in jobs.iterrows():
        cpu_norm = float(row["cpu_request"]) / max_cpu
        memory_norm = float(row["memory_request"]) / max_memory

        resource_requirement[int(i)] = round(
            min(1.0, 0.5 * cpu_norm + 0.5 * memory_norm),
            4,
        )

    return resource_requirement


def build_eligibility(jobs: pd.DataFrame) -> dict[int, list[int]]:
    """
    Build server eligibility.

    GPU jobs can run on GPU servers.
    """

    eligibility = {}

    for i, row in jobs.iterrows():
        if int(row["gpu_request"]) == 1:
            eligibility[int(i)] = GPU_SERVERS


    return eligibility


def build_jobs_json(jobs: pd.DataFrame) -> dict:
    """Build optimization-compatible jobs JSON."""

    I = list(range(len(jobs)))

    I_B = jobs[jobs["job_type"] == "batch"].index.astype(int).tolist()
    I_V = jobs[jobs["job_type"] == "interactive"].index.astype(int).tolist()
    I_C = jobs[jobs["is_critical"].astype(int) == 1].index.astype(int).tolist()

    eligibility = build_eligibility(jobs)
    resource_requirement = build_resource_requirements(jobs)

    d = {}
    r = {}
    a = {}
    b = {}
    q = {}
    rho = {}

    for i, row in jobs.iterrows():
        i = int(i)

        release_slot = seconds_to_release_slot(
            float(row["release_seconds"])
        )

        duration_slots = seconds_to_duration_slots(
            float(row["processing_duration_seconds"])
        )

        deadline_slot = seconds_to_deadline_slot(
            float(row["deadline_seconds"])
        )

        deadline_slot = max(
            deadline_slot,
            release_slot + duration_slots,
        )

        deadline_slot = min(
            deadline_slot,
            HORIZON_SLOTS,
        )

        d[i] = duration_slots
        r[i] = resource_requirement[i]
        a[i] = release_slot
        b[i] = deadline_slot
        q[i] = int(row["replica_count"])

        if str(row["job_type"]).lower() == "interactive":
            rho[i] = 5.0
        else:
            rho[i] = 3.0

    jobs_json = {
        "sets": {
            "I": I,
            "I_B": I_B,
            "I_V": I_V,
            "I_C": I_C,
            "E": [],
            "A": [],
            "G": [],
        },
        "eligibility": {
            str(key): value
            for key, value in eligibility.items()
        },
        "job_params": {
            "d": {
                str(key): value
                for key, value in d.items()
            },
            "r": {
                str(key): value
                for key, value in r.items()
            },
            "a": {
                str(key): value
                for key, value in a.items()
            },
            "b": {
                str(key): value
                for key, value in b.items()
            },
            "q": {
                str(key): value
                for key, value in q.items()
            },
            "rho": {
                str(key): value
                for key, value in rho.items()
            },
        },
        "metadata": {
            "source_file": str(INPUT_PATH),
            "slot_seconds": SLOT_SECONDS,
            "slot_duration_hours": SLOT_SECONDS / 3600,
            "horizon_seconds": HORIZON_SECONDS,
            "horizon_slots": HORIZON_SLOTS,
            "jobs_exported": len(jobs),
            "gpu_servers": GPU_SERVERS,
            "cpu_servers": CPU_SERVERS,
            "note": (
                "This file translates forecasted job-level workload into "
                "optimization model job parameters."
            ),
        },
    }

    return jobs_json


def save_json(data: dict, output_path: Path) -> None:
    """Save translated jobs JSON."""

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(
            data,
            file,
            indent=2,
        )


def main() -> None:
    """Run forecast-to-optimization JSON translation."""

    forecast_jobs = load_forecast_jobs(INPUT_PATH)

    validate_forecast_schema(forecast_jobs)

    cleaned_jobs = clean_forecast_jobs(forecast_jobs)

    if cleaned_jobs.empty:
        raise ValueError(
            "No valid jobs found after cleaning. "
            "Check the forecast output."
        )

    jobs_json = build_jobs_json(cleaned_jobs)

    save_json(
        data=jobs_json,
        output_path=OUTPUT_PATH,
    )

    print("\nForecast-to-optimization translation completed.")
    print(f"Input file: {INPUT_PATH}")
    print(f"Output file: {OUTPUT_PATH}")
    print(f"Jobs exported: {len(cleaned_jobs)}")
    print(f"Batch jobs: {len(jobs_json['sets']['I_B'])}")
    print(f"Interactive jobs: {len(jobs_json['sets']['I_V'])}")
    print(f"Critical jobs: {len(jobs_json['sets']['I_C'])}")


if __name__ == "__main__":
    main()
